# docker-compose.yml

version: '3.9'
services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test_pass
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: